version: "3.8"

services:
  backend:
    image: animesha/flask-backend
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: animesha/react-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
